# Docker Compose Securise - Template de Reference
# Conforme aux benchmarks CIS Docker

version: "3.9"

services:
  # ==========================================================================
  # APPLICATION PRINCIPALE
  # ==========================================================================
  app:
    image: myapp:1.0.0  # TOUJOURS specifier un tag precis
    build:
      context: .
      dockerfile: Dockerfile

    # --- SECURITE : Privileges ---
    cap_drop:
      - ALL                    # Supprimer TOUTES les capabilities par defaut
    cap_add:
      - NET_BIND_SERVICE       # Ajouter uniquement ce qui est necessaire

    security_opt:
      - no-new-privileges:true # Empecher l'escalade de privileges

    # --- SECURITE : Systeme de fichiers ---
    read_only: true            # Systeme de fichiers en lecture seule
    tmpfs:
      - /tmp:size=100M,mode=1777
      - /var/run:size=10M,mode=755

    # --- SECURITE : Utilisateur ---
    user: "1000:1000"          # UID:GID non-root

    # --- SECURITE : Ressources ---
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M

    # --- SECURITE : Reseau ---
    networks:
      - frontend
    ports:
      - "127.0.0.1:8080:8080"  # Ecoute uniquement sur localhost

    # --- SECURITE : Sante ---
    healthcheck:
      test: ["CMD", "/app/healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

    # --- SECURITE : PID ---
    pids_limit: 100            # Limiter le nombre de processus

    # --- Configuration ---
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info

    # NE JAMAIS mettre de secrets ici - utiliser Docker Secrets
    secrets:
      - db_password
      - api_key

    depends_on:
      db:
        condition: service_healthy

  # ==========================================================================
  # BASE DE DONNEES
  # ==========================================================================
  db:
    image: postgres:16-alpine  # Image minimale avec tag precis

    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID

    security_opt:
      - no-new-privileges:true

    # La DB a besoin d'ecrire, donc pas read_only
    # Mais on restreint les volumes
    volumes:
      - db_data:/var/lib/postgresql/data:rw

    networks:
      - backend              # Reseau isole, pas accessible depuis l'exterieur

    # PAS de ports exposes - accessible uniquement via le reseau interne
    expose:
      - "5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: myapp

    secrets:
      - source: db_password
        target: /run/secrets/db_password

# ==========================================================================
# SECRETS (Docker Swarm ou fichiers locaux en dev)
# ==========================================================================
secrets:
  db_password:
    file: ./secrets/db_password.txt  # En production: external: true
  api_key:
    file: ./secrets/api_key.txt

# ==========================================================================
# RESEAUX ISOLES
# ==========================================================================
networks:
  frontend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "true"
  backend:
    driver: bridge
    internal: true  # Pas d'acces Internet pour ce reseau

# ==========================================================================
# VOLUMES PERSISTANTS
# ==========================================================================
volumes:
  db_data:
    driver: local
